
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

# Helper functions

def lookup(cur: dict, struct: dict, attrs: list) -> int: 
    """
    Search for a given "group by" attribute value(s) in mf_struct. 
    If the value(s) doesn't exist then return -1, else return the index for that row.

    :param cur: Current row in the mf_struct.
    :param struct: The mf_struct.
    :param attrs: List of the grouping attributes that make up the key in the mf_struct.
    :return: Either the index of the matching row in mf_struct or -1 if not found.
    """

    key = () # compute key using row's grouping attribute values
    for attr in attrs:
        key += (cur[attr],)
    if key in struct.keys():
        return True
    return False



def add(cur: dict, struct: dict, attrs: list, aggs: list):
    """
    Adds new row to mf_struct.

    :param cur: Current row from base table.
    :param struct: The mf_struct the new row goes to.
    :param attrs: List of attributes whose values from cur will get added to the new row
    :param aggs: List of aggregates for each grouping variable
    """
    key = () # compute key using row's grouping attribute values
    for attr in attrs:
        key += (cur[attr],)
    value = dict()
    for agg in aggs:
        value[agg] = 0
    struct[key] = value



def output(struct: dict, attrs: list):
    """
    Print the rows of a given mf_struct.
    mf_struct's keys are the grouping attribute values themselves. Thus, we convert the keys into a dictionary where the key is the attribute's name (in attrs) and the value is the attribute's value (i.e. mf_struct key). Since the mf_struct's values are dictionaries that store the aggregates, we can combine the two dictionaries to produce a row of the mf_struct consisting of the grouping attributes and the aggregates.

    Example:

    For each mf_struct key-value pair -> 
    ("Sam") : {
         "1_sum_quant" : 10,
         "2_avg_quant" : 20,
    }

    Convert into a dictionary ->
    {"cust": "Sam", "1_sum_quant" : 10, "2_avg_quant" : 20}

    :param struct: The mf_struct we want to print.
    :param attrs: List of grouping attributes names.
    """
    

    ret = [] # stores rows of mf_struct
    for keys in struct.keys():
        d = {}
        for key, attr in zip(keys, attrs):
            d[attr] = key
    # combine dictionary of keys with the keys' dictionary 
    d.update(struct.get(keys))
    ret.append(d)    
    print(tabulate.tabulate(ret, headers="keys", tablefmt="psql"))
    

def query():
    load_dotenv() # reads the .env file

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales") # prints all the rows in the data table
    
    _global = []
    
    mf_struct = {
        
    }
    
    num_rows = 1 # keeps track of how many rows the mf_struct has
    
    for row in cur:
    #     lookup(row, mf_struct, ['cust', 'prod'])
        add(row, mf_struct, ['cust', 'prod'], ['1_sum_quant', '1_avg_quant', '2_sum_quant', '3_sum_quant', '3_avg_quant'])
        break

    output(mf_struct, ['cust', 'prod'])
    # print(mf_struct)
    

    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql") # returns data as a table

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    